### ISSUE TITLE
Unhandled Exception in Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware

### ISSUE THREAD

**Issue by saigkill** [shawnwildermuth/WilderBlog#40]
After launching the blog in Visual Studio i'm getting:

Hosting environment: Development
Content root path: C:\Users\Sasch\OneDrive\source\repos\Visual_Studio\saschamannsde\src\WilderBlog
Now listening on: http://localhost:54451
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches:

WilderBlog.Controllers.RootController.Index (WilderBlog)
WilderBlog.Controllers.TalksController.Index (WilderBlog)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at WilderBlog.Services.UrlRewriter.Invoke(HttpContext context) in C:\Users\Sasch\OneDrive\source\repos\Visual_Studio\saschamannsde\src\WilderBlog\Services\UrlRewriter.cs:line 43
   at WilderMinds.MetaWeblog.MetaWeblogMiddleware.Invoke(HttpContext context, MetaWeblogService service)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

C:\Users\Sasch\OneDrive\source\repos\Visual_Studio\saschamannsde\src\WilderBlog\bin\Debug\netcoreapp3.1\WilderBlog.exe (Prozess "6300") wurde mit Code "-1" beendet.

What could run into this error? 
My current codebase is: [https://github.com/saigkill/WilderBlog](https://github.com/saigkill/WilderBlog)

**Comment by shawnwildermuth** [comment]
You need a route controller for your Talk controller so that it doesn't collide with the Root Controller.

```
// From my Repo
 [Route("[controller]")]
  public class TalkController : Controller
  {
```

**Comment by saigkill** [comment]
Thank you, that was it :-)
